print("hello people")
print('hii everyone')
print("hey 'guess' whatsaap")
print('How "are" you ?')
print("STRING = Collection of cheacter inside Double quotes or 'Single quotes'\n")
print("You can use 'Single quotes inside Double quotes'\n \t \t or \n'Double quotes inside Single quotes'\n ")
print("BUT don't use double quotes to double quotes and single quotes to single quotes because error invalid syntax show\n")
print("This is too \"much\" yaar no error because  back slash use ish called \"ESCAPE SEQUENCES\" \n") 
print('I\'m Mohini')